alias rm='rm -i'
alias emacs='vim'
alias diff='colordiff'
alias lc='ls -Chal'
alias lh='ls -hl'
alias lt='ls -halt'
alias lr='ls -haltr'
alias mount='mount | column -t'
alias pscpu='ps auxf | sort -nr -k 3'
alias wtf='ps auxf | sort -nr -k 3 | head -10 && ps auxf | sort -nr -k 4 | head -10'
alias pyclean='find . | grep -E "(__pycache__|\.pyc|\.pyo$)" | xargs rm -rf'
alias tputcols=$'printf \'%*s\n\' "${COLUMNS:-$(tput cols)}" \'\' | tr \' \' -'
# Yum
alias yeet='yum remove'
alias yoink='yum install'
alias yup='yum check-update && yum update'
alias yep='yum --enablerepo=epel install'
# iptables
alias lsacl='sudo /sbin/iptables -L -n -v --line-numbers'
alias aclin='sudo /sbin/iptables -L INPUT -n -v --line-numbers'
alias aclout='sudo /sbin/iptables -L OUTPUT -n -v --line-numbers'
alias aclfwd='sudo /sbin/iptables -L FORWARD -n -v --line-numbers'
# Git status / log
alias gats='git status'
alias gog='git log'
alias gag='git dag | head'
alias gitt='git log --oneline --decorate --all --graph --color'
alias gg='git pretty | head'
alias ggg='git pretty | head -n 40'
alias gggg='git pretty'
alias what=$'gats && gg && printf \'\n\''
# Git commands
alias gitm='git commit -m'
alias gita='git commit -add .'
alias gitam='git add -A && git commit -m'
alias gcob='git checkout -b'
alias glist='git stash list'
alias getch='git fetch'
alias gall='git fetch --all'
alias geads='git log --oneline --decorate --all --graph --color --simplify-by-decoration'
alias branches='git branch -vv'
alias gainline='git co mainline && git pull && git co -'
alias mygit='git config user.name "Shelby Skalnik" && git config user.email "sskalnik@sskalnik.com"'
alias gnuke='git reset --hard && git clean -df'
alias gamend='git add -A && git commit --amend'
# Onica / Rackspace
alias sso-aws='sso-list --json | jq --unbuffered -r '\''.accounts[] | .externalId + "@" + .key + "@" + .name'\'' | sort -k 2 -t '\''@'\'' | column -t -s'\''@'\'''
